name: lift_cube_depth_isaac

shape_meta:
  # acceptable types: rgb, low_dim, depth
  obs:
    agentview_depth:
      shape: [1, 128, 128]
      type: depth
    robot0_eef_depth:
      shape: [1, 128, 128]
      type: depth
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [7]

task_id: IIL-Lift-Cube-v0
project: IIL-Lift-Cube-v0
dataset_type: ph
dataset_path: ${oc.env:HOME}/master/datasets/lift_cube_v0/dataset_obs_gen.hdf5
abs_action: False
topk:
  monitor_key: test_mean_score
  mode: max
  k: 3
  format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'

env_runner:
  _target_: isaac_imitation_learning.robodiff.env_runner.isaac_lab_image_runner.IsaacLabImageRunner
  env_wrapper:
    _partial_: True
    _target_: isaac_imitation_learning.robodiff.utils.isaac_lab_image_wrapper.IsaacLabImageWrapper
    env: null
    shape_meta: ${...shape_meta}
  dataset_path: ${..dataset_path}
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_seed: 100000
  # use python's eval function as resolver, single-quoted string as argument
  max_steps: ${eval:'250 if "${task.dataset_type}" == "mh" else 200'}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_video: True
  render_obs_key: 'agentview_image'
  fps: 30
  crf: 22
  abs_action: ${..abs_action}
  tqdm_interval_sec: 1.0
  n_envs: 28
  dummy_rollout: False
  persistent_env: True
  isaac_args: ${..isaac}

dataset:
  _target_: isaac_imitation_learning.robodiff.dataset.isaac_lab_replay_dataset.IsaacLabReplayDataset
  shape_meta: ${..shape_meta}
  dataset_path: ${..dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: ${..abs_action}
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: False
  seed: 42
  val_ratio: 0.02

  isaac:
  headless: True
  livestream: -1
  enable_cameras: True
  device: ${device}
  cpu: False
  verbose: False
  info: False
  experience: ""
  kit_args: ""
